version: "3.6"

networks:
  app:
    driver: bridge

services:
  server:
    build: .
    container_name: server
    stdin_open: true
    tty: true
    volumes:
      - .:/home
    ports:
      - "3001:8000"
    # depends_on:
    #   - database
    networks:
      - app

  database:
    image: postgres
    container_name: database_post
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=api
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app 